name: "Release pre built"
description: "Builds ex_doc scripts"
inputs:
  otp:
    description: "The major OTP version"
  otp_version:
    description: "The exact OTP version (major.minor[.patch])"
runs:
  using: "composite"
  steps:
    - uses: erlef/setup-beam@v1.18.2
      with:
        otp-version: ${{ inputs.otp_version }}
        elixir-version: "1.17.3"
    - name: Install system dependencies
      shell: bash
      run: sudo apt-get install -y libsodium-dev
    - name: Install Protobuf dependencies
      shell: bash
      run: sudo apt install -y protobuf-compiler
    - name: Build ex_doc
      shell: bash
      run: |
        mix deps.get
        mix escript.install hex protobuf --force
        PATH="$HOME/.mix/escripts:$PATH" mix release
        cd _build/dev/rel/
        tar czf anoma_otp_${{ inputs.otp }}.tar.gz anoma
        shasum -a 1 anoma_otp_${{ inputs.otp }}.tar.gz > anoma_otp_${{ inputs.otp }}.tar.gz.sha1sum
        shasum -a 256 anoma_otp_${{ inputs.otp }}.tar.gz > anoma_otp_${{ inputs.otp }}.tar.gz.sha256sum
        echo "Hmm $PWD"
        echo "$PWD" >> $GITHUB_PATH
