name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  create_release:
    continue-on-error: true
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create release
        run: |
          echo "Creating release..."
          gh release create \
            --repo ${{ github.repository }} \
            --title ${{ github.ref_name }} \
            ${{ github.ref_name }}

  release_pre_built:
    needs: create_release
    strategy:
      fail-fast: true
      matrix:
        include:
          - otp: 27
            otp_version: "27.0"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - uses: ./.github/workflows/release_pre_built
        with:
          otp_version: ${{ matrix.otp_version }}
          otp: ${{ matrix.otp }}

      - name: Upload Pre-built
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd _build/dev/rel/
          gh release upload --clobber "${{ github.ref_name }}" \
            anoma_otp_${{ matrix.otp }}.tar.gz \
            anoma_otp_${{ matrix.otp }}.tar.gz.sha{1,256}sum \
  build-docs:
    name: build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/setup
        with:
          fail-on-failure: ${{ true }}

      - uses: ./.github/workflows/docs
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          release: ${{ true }}
